### ISSUE TITLE
Centos Installation

### ISSUE THREAD

**Issue by sudharani-m** [cschwede/django-swiftbrowser#29]
Hello,

I have installed this bundle on centos machine.

1. Do i need to install swift client before installing this package
2. What should be content of swiftbrowser.settings?

**Comment by sudharani-m** [comment]
Can anyone help me here?

**Comment by manoj-ms** [comment]
Swift client needs to be installed.

Setting files should have information about auth URL and controller node details of your open stack installation

Sent from my iPhone

On 15-Dec-2016, at 8:06 PM, sudharani-m <notifications@github.com<mailto:notifications@github.com>> wrote:


Can anyone help me here?

-

**Comment by sudharani-m** [comment]
Hi Manoj, I tired different options. My url.py I have updated to include swift urls. However I getting import error. Pls can you help me here?

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls, swiftbrowser.urls),
    ]

import swiftbrowser.urls
urlpatterns = [
    url(r'^', include(swiftbrowser.urls),
]

python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f08956d30c8>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/swiftbrowser/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns

**Comment by manoj-ms** [comment]
Import errors may be for various reasons. From what I see, import command should work though there is a syntactic errors in other part of program.

Simple import command should work. I would debug this in the python shell to verify why import isn't working. Perhaps if you can upload your project somewhere we can have a look at it.

Sent from my iPhone

On 22-Dec-2016, at 2:44 PM, sudharani-m <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Manoj, I tired different options. My url.py I have updated to include swift urls. However I getting import error. Pls can you help me here?

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
url(r'^admin/', admin.site.urls, swiftbrowser.urls),
]

import swiftbrowser.urls
urlpatterns = [
url(r'^', include(swiftbrowser.urls),
]

python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f08956d30c8>
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
fn(*args, **kwargs)
File "/usr/lib64/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
self.check(display_num_errors=True)
File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 374, in check
include_deployment_checks=include_deployment_checks,
File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
return checks.run_checks(**kwargs)
File "/usr/lib64/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
new_errors = check(app_configs=app_configs)
File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
return check_resolver(resolver)
File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
for pattern in resolver.url_patterns:
File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/lib64/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/usr/lib/python2.7/site-packages/swiftbrowser/urls.py", line 1, in
from django.conf.urls import patterns, url
ImportError: cannot import name patterns

-

**Comment by sudharani-m** [comment]
Hi Manoj, Can I set up some quick call to discuss on this?

**Comment by manoj-ms** [comment]
We can one next week.

Sent from my iPhone

On 02-Jan-2017, at 10:41 AM, sudharani-m <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Manoj, Can I set up some quick call to discuss on this?

-

**Comment by hoogenm** [comment]
The `import patterns` ImportError might be caused by an incompatibility with django 1.10. You could try `pip install django==1.09` to make sure django 1.09 is installed (then try to run swiftbrowser again). For me that worked to get swiftbrowser running without import errors (although I get an issue similar to #15).
